version: "3.3"

services:
  api:
    build: .
    volumes:
      - ./api:/var/www/html
    ports:
      - 8000:8080
    networks:
      - backend
  postgres:
    image: postgres:11-alpine
    volumes:
         - "./data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=develop
    ports:
     - "5432:5432"
    networks:
     - backend

networks:
  backend:
    driver: "bridge"